---

- name: Ensure k3s service unit file is present on control plane
  template:
    src: k3s.service.j2
    dest: /etc/systemd/system/k3s.service
  when: k3s_control_node
  notify:
    - reload systemctl

- meta: flush_handlers

- name: Ensure k3s is symlinked into the installation destinations
  file:
    src: "{{ k3s_install_dir }}/k3s-{{ k3s_release_version }}"
    dest: "{{ k3s_install_dir }}/{{ item }}"
    state: link
  notify:
    - restart k3s
  loop:
    - k3s
    - kubectl
    - crictl

- name: Ensure k3s control plane is started
  service:
    name: k3s
    state: started
    enabled: true
  when: k3s_control_node
