---

- name: Ensure Docker repository is uninstalled
  apt_repository:
    filename: docker-ce
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    update_cache: false
    state: absent

- name: Ensure Docker APT key is uninstalled
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: absent

- name: Ensure Docker prerequisites are uninstalled
  apt:
    name: "{{ item }}"
    state: absent
  register: ensure_docker_prerequisites_uninstalled
  until: ensure_docker_prerequisites_uninstalled is succeeded
  retries: 3
  delay: 10
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - "{{ 'gnupg2' if ansible_distribution == 'Debian' else 'gnupg-agent' }}"
    - software-properties-common
